import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { useSession, signIn, signOut } from "next-auth/react";
import styles from '../styles/Home.module.scss';

export default function Home() {

  const { data: session } = useSession();
  const router = useRouter();

  // console.log(session.user);
  console.log(session);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Testing NextAuth
        </p>

        <div>
          {
            session ?
              <>
                <p>
                  Signed in as {session.user.email}
                </p>
                <img src={session.user.image} />
                <br />
                <button onClick={() => signOut()}>Sign out</button>
              </> :
              <>
                <p>
                  Not signed in
                </p>
                <br />
                <button onClick={() => signIn()}>Sign in</button>
              </>
          }

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
